stages:
  load_data:
    cmd: python -m src.load_data
    deps:
    - src/load_data.py
    outs:
    - data/raw/diabetes.parquet
  data_split:
    cmd: python -m src.data_split
    deps:
    - src/data_split.py
    - data/raw
    outs:
    - data/processed/train.parquet
    - data/processed/val.parquet
    - data/processed/test.parquet
  training:
    cmd: python -m src.training
    deps:
    - src/training.py
    - data/processed
    outs:
    - models/model.pkl
  evaluation:
    cmd: python -m src.evaluation
    deps:
    - src/evaluation.py
    - models/model.pkl
    - data/processed
    outs:
    - eval
metrics:
- eval/metrics.json
plots:
- eval/plots/metrics:
    x: step
- eval/plots/images
